version: "3.9"
services:
  inventory-service:
    build: ./inventoryservice
    ports:
      - "8081:8081"
  billing-service:
    build: ./billingservice
    ports:
      - "8082:8082"
    depends_on:
      - inventory-service
    environment:
      # aqu√≠ ya no es localhost, es el nombre del servicio
      - INVENTORY_URL=http://inventory-service:8081
